---
- name: Setup manager
  hosts: swarm-managers
  become: yes
  roles:
  - docker_install
  - swarm-manager

- name: Setup workers
  hosts: swarm-workers
  become: yes
  roles:
  - docker_install
  - swarm-worker-1
  - swarm-worker-2  

- name: nginx
  hosts: nginx
  become: yes
  roles: 
  - nginx    