CREATE TABLE IF NOT EXISTS gacha
(
id INTEGER NOT NULL AUTO_INCREMENT,
star VARCHAR(10) NOT NULL,
affluence VARCHAR(10) NOT NULL,
names VARCHAR(10) NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;