version: '3.7'
services:
  service1:
    image: jcashen/app-1
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    image: jcashen/app-2
    build: ./service2
    ports:
    - target: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service3:
    image: jcashen/app-3
    build: ./service3
    ports:
    - target: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service4:
    image: jcashen/app-4
    build: ./service4
    ports:
    - target: 5003
      protocol: tcp
    deploy:
      replicas: 3