---
- hosts: all
  become: yes
  roles:
  - docker_install

- name: Setup manager
  hosts: swarm-managers
  become: yes
  roles:
  - swarm-managers

  - name: Setup workers
  hosts: swarm-workers
  become: yes
  roles:
  - swarm-workers 

  