---
- hosts: all
  become: yes
  roles:
  - docker_install

- name: Setup manager
  hosts: swarm-manager
  become: yes
  roles:
  - swarm_manager

  - name: Setup workers
  hosts: swarm-workers
  become: yes
  roles:
  - swarm_worker 

  